# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: "CI"

on:
  push:
    branches:
      - "main"
      - "pull-request/[0-9]+"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.10'
      - name: "Running Lint" 
        run: |
          pip install hatch
          hatch run lint:check

  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.10'
      - name: "Building Docs" 
        run: |
          pip install hatch
          hatch run docs:build

  test_linux_amd64_gpu_h100_latest:
    runs-on: linux-amd64-gpu-h100-latest-1
    container:
      image: nvcr.io/nvidia/pytorch:25.09-py3 
      options: "--cap-add=SYS_ADMIN --gpus all"
    steps:
      - uses: actions/checkout@v5
      - name: "Running Tests" 
        run: |
          pip install hatch
          hatch run test_cu13:run
